// "Countryside" — inspired by Flash-era top-down rural racing tracks.
// Layout reads counter-clockwise from the start/finish line:
//
//   start straight  →  fast right sweeper  →  S-chicane  →
//   long left  →  tight hairpin  →  uphill kink  →  back to start
//
// Decorations are auto-generated by Track from a deterministic seed.

export default {
  name: 'Countryside',
  halfWidth: 56,
  laps: 3,
  decorationDensity: 0.55,
  decorationSeed: 1337,
  controlPoints: [
    [    0,     0],   // start/finish line
    [  220,   -10],   // start straight
    [  430,   -25],
    [  610,    30],   // entry to right sweeper
    [  730,   140],
    [  760,   280],   // mid sweeper
    [  690,   400],
    [  560,   460],   // entry to S-chicane
    [  450,   400],   // chicane left apex
    [  340,   470],   // chicane right apex
    [  170,   520],
    [  -50,   540],   // long left curve
    [ -260,   500],
    [ -420,   420],   // approach hairpin
    [ -520,   280],   // hairpin entry
    [ -510,   120],   // hairpin apex
    [ -420,    30],   // hairpin exit
    [ -280,   -10],   // back straight kink
    [ -140,   -30]
  ]
};
